/**
 * Component 16D: Spec-to-Code Scaffolder
 *
 * Takes a TYPE 3 specification and generates a TypeScript file skeleton
 * with JSDoc headers, import statements, interface definitions, function
 * stubs, and a companion .test.ts file with describe blocks.
 *
 * Designed for VitalMatrix engine pipeline authoring — scaffolds files
 * that align with the 7-node (N1-N7), 5-zone (Z1-Z5), 6-stack (S1-S6)
 * architecture and the FLINT-APEX-STRIDE-RIL-CADENCE-CIL-VISTA pipeline.
 *
 * @module c16d-spec-to-code-scaffolder
 */

import { VM_BRAND } from './brand-config';

// --- Types ---

/** Input/output field definition within a specification. */
export interface FieldDef {
  name: string;
  type: string;
}

/** TYPE 3 specification input for scaffolding. */
export interface SpecInput {
  /** Human-readable feature name, e.g. "Terrain Resilience Score" */
  featureName: string;
  /** Feature identifier, e.g. "F42" */
  featureId: string;
  /** Brief description of what the feature computes */
  description: string;
  /** Input fields consumed by the feature */
  inputs: FieldDef[];
  /** Output fields produced by the feature */
  outputs: FieldDef[];
  /** Dependencies — other feature IDs or module names */
  dependencies: string[];
  /** Which nodes this feature is relevant to (e.g. ["N1","N3","N7"]) */
  nodeRelevance: string[];
  /** Which zones this feature is relevant to (e.g. ["Z2","Z4"]) */
  zoneRelevance: string[];
}

/** Result of the scaffolding operation. */
export interface ScaffoldResult {
  /** Generated main .ts file content */
  mainFile: string;
  /** Generated companion .test.ts file content */
  testFile: string;
  /** List of TypeScript interface/type names generated */
  typesGenerated: string[];
}

// --- Helpers ---

/**
 * Converts a feature name to PascalCase for use in interface names.
 * E.g. "Terrain Resilience Score" -> "TerrainResilienceScore"
 */
function toPascalCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .split(/\s+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

/**
 * Converts a feature name to camelCase for use in function names.
 * E.g. "Terrain Resilience Score" -> "terrainResilienceScore"
 */
function toCamelCase(name: string): string {
  const pascal = toPascalCase(name);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * Converts a feature name to kebab-case for file names.
 * E.g. "Terrain Resilience Score" -> "terrain-resilience-score"
 */
function toKebabCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .map((w) => w.toLowerCase())
    .join('-');
}

/**
 * Builds the JSDoc header block for a generated file.
 */
function buildJSDocHeader(spec: SpecInput): string {
  const lines: string[] = [
    '/**',
    ` * ${spec.featureName} (${spec.featureId})`,
    ` * ${spec.description}`,
    ' *',
    ` * Nodes: ${spec.nodeRelevance.join(', ') || 'None specified'}`,
    ` * Zones: ${spec.zoneRelevance.join(', ') || 'None specified'}`,
    ` * Dependencies: ${spec.dependencies.join(', ') || 'None'}`,
    ' *',
    ` * Generated by VitalMatrix Content Studio — Spec-to-Code Scaffolder`,
    ` * ${VM_BRAND.credentials.company} | ${VM_BRAND.platform.ico}`,
    ` * ${VM_BRAND.regulatoryFooter}`,
    ' */',
  ];
  return lines.join('\n');
}

// --- Core Functions ---

/**
 * Generates a TypeScript interface definition from a list of fields.
 *
 * @param interfaceName - The PascalCase name for the interface.
 * @param fields - Array of field definitions (name + type).
 * @returns TypeScript interface source code.
 */
export function generateInterfaceFromSpec(
  interfaceName: string,
  fields: FieldDef[],
): string {
  if (fields.length === 0) {
    return `export interface ${interfaceName} {\n  // No fields defined — update from specification\n}`;
  }

  const fieldLines = fields
    .map((f) => `  /** ${f.name} */\n  ${f.name}: ${f.type};`)
    .join('\n');

  return `export interface ${interfaceName} {\n${fieldLines}\n}`;
}

/**
 * Generates a companion .test.ts file from the specification.
 * Includes describe blocks for each output, input validation,
 * and architecture-element coverage markers.
 *
 * @param spec - The TYPE 3 specification.
 * @returns Test file content as a string.
 */
export function generateTestFileFromSpec(spec: SpecInput): string {
  const fnName = toCamelCase(spec.featureName);
  const pascalName = toPascalCase(spec.featureName);
  const kebabName = toKebabCase(spec.featureName);
  const inputInterface = `${pascalName}Input`;
  const outputInterface = `${pascalName}Output`;

  const lines: string[] = [
    '/**',
    ` * Tests for ${spec.featureName} (${spec.featureId})`,
    ` * Generated by VitalMatrix Content Studio — Spec-to-Code Scaffolder`,
    ' */',
    '',
    `import { ${fnName}, type ${inputInterface}, type ${outputInterface} } from './${kebabName}';`,
    '',
    `describe('${spec.featureName} (${spec.featureId})', () => {`,
  ];

  // Node relevance test stubs
  for (const node of spec.nodeRelevance) {
    lines.push(`  describe('${node} relevance', () => {`);
    lines.push(`    it('should produce valid output for ${node} scenarios', () => {`);
    lines.push(`      // TODO: implement ${node} test case`);
    lines.push(`    });`);
    lines.push(`  });`);
    lines.push('');
  }

  // Zone relevance test stubs
  for (const zone of spec.zoneRelevance) {
    lines.push(`  describe('${zone} relevance', () => {`);
    lines.push(`    it('should handle ${zone} zone-specific logic', () => {`);
    lines.push(`      // TODO: implement ${zone} test case`);
    lines.push(`    });`);
    lines.push(`  });`);
    lines.push('');
  }

  // Input validation tests
  lines.push(`  describe('Input validation', () => {`);
  for (const input of spec.inputs) {
    lines.push(`    it('should validate ${input.name} (${input.type})', () => {`);
    lines.push(`      // TODO: implement validation test for ${input.name}`);
    lines.push(`    });`);
    lines.push('');
  }
  lines.push(`  });`);
  lines.push('');

  // Output tests
  lines.push(`  describe('Output correctness', () => {`);
  for (const output of spec.outputs) {
    lines.push(`    it('should compute ${output.name} correctly', () => {`);
    lines.push(`      // TODO: implement output test for ${output.name}`);
    lines.push(`    });`);
    lines.push('');
  }
  lines.push(`  });`);
  lines.push('');

  // Dependency tests
  if (spec.dependencies.length > 0) {
    lines.push(`  describe('Dependencies', () => {`);
    for (const dep of spec.dependencies) {
      lines.push(`    it('should integrate with ${dep}', () => {`);
      lines.push(`      // TODO: implement dependency integration test for ${dep}`);
      lines.push(`    });`);
      lines.push('');
    }
    lines.push(`  });`);
    lines.push('');
  }

  // Edge cases
  lines.push(`  describe('Edge cases', () => {`);
  lines.push(`    it('should handle missing optional fields', () => {`);
  lines.push(`      // TODO: implement edge case`);
  lines.push(`    });`);
  lines.push('');
  lines.push(`    it('should handle boundary values', () => {`);
  lines.push(`      // TODO: implement boundary test`);
  lines.push(`    });`);
  lines.push(`  });`);

  lines.push(`});`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Scaffolds a complete TypeScript file and companion test file from a
 * TYPE 3 specification. The main file includes JSDoc header, imports,
 * interface definitions, function stubs with TODO comments, and exports.
 *
 * @param spec - The TYPE 3 specification to scaffold from.
 * @returns ScaffoldResult containing mainFile, testFile, and typesGenerated.
 */
export function scaffoldFromSpec(spec: SpecInput): ScaffoldResult {
  const pascalName = toPascalCase(spec.featureName);
  const fnName = toCamelCase(spec.featureName);
  const inputInterface = `${pascalName}Input`;
  const outputInterface = `${pascalName}Output`;
  const configInterface = `${pascalName}Config`;

  const typesGenerated: string[] = [inputInterface, outputInterface, configInterface];

  // --- Build main file ---
  const mainLines: string[] = [];

  // JSDoc header
  mainLines.push(buildJSDocHeader(spec));
  mainLines.push('');

  // Imports
  const importLines: string[] = [];
  for (const dep of spec.dependencies) {
    const depKebab = toKebabCase(dep);
    importLines.push(`// import { /* needed exports */ } from './${depKebab}';  // TODO: resolve dependency ${dep}`);
  }
  if (importLines.length > 0) {
    mainLines.push('// --- Dependencies ---');
    mainLines.push(...importLines);
    mainLines.push('');
  }

  // Interfaces
  mainLines.push('// --- Types ---');
  mainLines.push('');
  mainLines.push(generateInterfaceFromSpec(inputInterface, spec.inputs));
  mainLines.push('');
  mainLines.push(generateInterfaceFromSpec(outputInterface, spec.outputs));
  mainLines.push('');

  // Config interface
  mainLines.push(`export interface ${configInterface} {`);
  mainLines.push(`  /** Enable verbose logging during computation */`);
  mainLines.push(`  verbose?: boolean;`);
  if (spec.nodeRelevance.length > 0) {
    mainLines.push(`  /** Restrict computation to specific nodes */`);
    mainLines.push(`  restrictToNodes?: (${spec.nodeRelevance.map((n) => `'${n}'`).join(' | ')})[];`);
  }
  if (spec.zoneRelevance.length > 0) {
    mainLines.push(`  /** Restrict computation to specific zones */`);
    mainLines.push(`  restrictToZones?: (${spec.zoneRelevance.map((z) => `'${z}'`).join(' | ')})[];`);
  }
  mainLines.push(`}`);
  mainLines.push('');

  // Main function stub
  mainLines.push('// --- Core Logic ---');
  mainLines.push('');
  mainLines.push('/**');
  mainLines.push(` * Computes ${spec.featureName} from the provided input.`);
  mainLines.push(' *');
  mainLines.push(` * @param input - ${inputInterface} containing all required fields.`);
  mainLines.push(` * @param config - Optional ${configInterface} for runtime overrides.`);
  mainLines.push(` * @returns ${outputInterface} with computed results.`);
  mainLines.push(' */');
  mainLines.push(`export function ${fnName}(`);
  mainLines.push(`  input: ${inputInterface},`);
  mainLines.push(`  config?: ${configInterface},`);
  mainLines.push(`): ${outputInterface} {`);
  mainLines.push(`  // TODO: implement ${spec.featureName} (${spec.featureId})`);
  mainLines.push(`  // Architecture context: Nodes ${spec.nodeRelevance.join(', ')}, Zones ${spec.zoneRelevance.join(', ')}`);
  mainLines.push('');

  // Stub return
  if (spec.outputs.length > 0) {
    mainLines.push(`  return {`);
    for (const out of spec.outputs) {
      const defaultVal = getDefaultForType(out.type);
      mainLines.push(`    ${out.name}: ${defaultVal}, // TODO: compute`);
    }
    mainLines.push(`  };`);
  } else {
    mainLines.push(`  return {} as ${outputInterface}; // TODO: implement`);
  }

  mainLines.push(`}`);
  mainLines.push('');

  // Validation helper stub
  mainLines.push('/**');
  mainLines.push(` * Validates the input before processing.`);
  mainLines.push(' *');
  mainLines.push(` * @param input - ${inputInterface} to validate.`);
  mainLines.push(` * @returns Array of validation error messages (empty if valid).`);
  mainLines.push(' */');
  mainLines.push(`export function validate${pascalName}Input(`);
  mainLines.push(`  input: ${inputInterface},`);
  mainLines.push(`): string[] {`);
  mainLines.push(`  const errors: string[] = [];`);
  mainLines.push('');
  for (const inp of spec.inputs) {
    mainLines.push(`  // TODO: validate ${inp.name} (${inp.type})`);
  }
  mainLines.push('');
  mainLines.push(`  return errors;`);
  mainLines.push(`}`);
  mainLines.push('');

  // Export block at end
  mainLines.push(`// --- Exports ---`);
  mainLines.push(`// Main function and types are exported inline above.`);
  mainLines.push(`// Re-export summary for barrel files:`);
  mainLines.push(`// export { ${fnName}, validate${pascalName}Input, type ${inputInterface}, type ${outputInterface}, type ${configInterface} };`);
  mainLines.push('');

  // --- Build test file ---
  const testFile = generateTestFileFromSpec(spec);

  return {
    mainFile: mainLines.join('\n'),
    testFile,
    typesGenerated,
  };
}

// --- Internal Helpers ---

/**
 * Returns a sensible default value string for a given TypeScript type.
 * Used in function stubs to produce compilable code.
 */
function getDefaultForType(tsType: string): string {
  const normalised = tsType.trim().toLowerCase();

  if (normalised === 'string') return "''";
  if (normalised === 'number') return '0';
  if (normalised === 'boolean') return 'false';
  if (normalised.endsWith('[]')) return '[]';
  if (normalised === 'date') return 'new Date()';
  if (normalised === 'null') return 'null';
  if (normalised === 'undefined') return 'undefined';
  if (normalised.startsWith('record<')) return '{}';
  if (normalised.startsWith('map<')) return 'new Map()';
  if (normalised.startsWith('set<')) return 'new Set()';

  // For union types or complex types, use a cast
  return `undefined as unknown as ${tsType}`;
}
