/**
 * Component 6: T-01 Output Template Generator
 * CRITICAL PRODUCTIVITY FEATURE
 *
 * Automatically applies ALL 7 T-01 Phase 1 restrictions to any clinical output.
 * Every practitioner-facing document must pass through this before delivery.
 *
 * T-01 Rules applied:
 *  W5-1 [PHASE 1 TEMPORARY]: Title = "Terrain Support Considerations"
 *  W5-2 [PHASE 1 TEMPORARY]: Fixed opening line (not editable)
 *  W5-3 [PERMANENT: NEVER REVERT]: Mandatory protective header before any clinical content
 *  W5-4 [PERMANENT: NEVER REVERT]: Mandatory blank Practitioner Clinical Decision section at end
 *  W5-5 [PHASE 1 TEMPORARY]: CascadeIQ band labels SUPPRESSED -> "Terrain Resilience: X/10"
 *  W5-6 [PHASE 1 TEMPORARY]: DRD display language: Driver -> "Highest burden zone", Reactor -> "Secondary burden zone"
 *  W5-7 [PHASE 1 TEMPORARY]: Content filter: supplements, dietary, lifestyle ONLY. Zero pharmaceutical.
 *
 * T-01a: DRD display language applies to ALL practitioner-visible materials
 * T-01b: No new clinical claims beyond CS01-CS08
 */

import { VM_BRAND } from './brand-config';

// --- Constants ---

export const T01_TITLE = 'Terrain Support Considerations';

export const T01_OPENING_LINE = 'Based on the terrain assessment, the following support considerations are noted for your review.';

export const T01_PROTECTIVE_HEADER = `IMPORTANT NOTICE

This document is generated by VitalMatrix\u2122, a terrain intelligence platform. It is provided as a support tool for qualified healthcare practitioners only. The content does not constitute medical advice, diagnosis, or treatment recommendations. All clinical decisions remain the sole responsibility of the treating practitioner.

VitalMatrix\u2122 does not replace clinical judgement. The terrain assessment and support considerations presented below are derived from practitioner-entered data and are subject to the limitations of that data. No automated system can account for all clinical variables.

This output has not been reviewed by a regulatory body. VitalMatrix Ltd is registered with the ICO (ZC101813). For practitioner use only.`;

export const T01_PRACTITIONER_DECISION_SECTION = `PRACTITIONER CLINICAL DECISION

The following section is for the treating practitioner to complete. VitalMatrix\u2122 does not pre-populate, suggest, or influence any entries in this section.

Clinical Assessment:
[Practitioner to complete]

Treatment Plan:
[Practitioner to complete]

Referrals:
[Practitioner to complete]

Follow-up Schedule:
[Practitioner to complete]

Practitioner Signature and Date:
[Practitioner to complete]`;

// --- Types ---

export interface ClinicalContent {
  zones: ZoneOutput[];
  cascadeStacks?: CascadeStackOutput[];
  terrainResilience: number;  // 0-10 display scale
  drdDesignation?: DrdOutput;
  supportConsiderations: SupportConsideration[];
}

export interface ZoneOutput {
  zone: string;        // Z1-Z5
  zoneName: string;
  score: number;       // 0-10 display scale
  status: 'Active' | 'Borderline (near threshold)' | 'Inactive';
  borderlineTooltip?: string;
}

export interface CascadeStackOutput {
  stack: string;       // S1-S6
  label: string;       // evidence tier applied
  active: boolean;
}

export interface DrdOutput {
  highestBurdenZone: string;     // W5-6: never "Driver"
  secondaryBurdenZone?: string;  // W5-6: never "Reactor"
}

export interface SupportConsideration {
  category: 'supplement' | 'dietary' | 'lifestyle';  // W5-7: ONLY these 3
  description: string;
  evidenceTier: string;
  targetZone: string;
}

// --- W5-5: CascadeIQ Band Label Suppression ---

export function formatTerrainResilience(score: number): string {
  // W5-5: Replace CascadeIQ band labels with simple score
  return `Terrain Resilience: ${score}/10`;
}

// --- W5-6: DRD Display Language ---

export function formatDrdDesignation(drd: DrdOutput): string {
  // W5-6: Driver -> "Highest burden zone", Reactor -> "Secondary burden zone"
  let output = `Highest burden zone: ${drd.highestBurdenZone}`;
  if (drd.secondaryBurdenZone) {
    output += `\nSecondary burden zone: ${drd.secondaryBurdenZone}`;
  }
  return output;
}

// --- W5-7: Content Filter ---

export function filterPharmaceutical(considerations: SupportConsideration[]): SupportConsideration[] {
  // W5-7: supplements, dietary, lifestyle ONLY. Zero pharmaceutical.
  // Pharmaceutical items retained in data layer but hidden from output
  return considerations.filter(c =>
    c.category === 'supplement' ||
    c.category === 'dietary' ||
    c.category === 'lifestyle'
  );
}

// --- Borderline Tooltip (D-38) ---

export const BORDERLINE_TOOLTIP = 'This zone has not met the activation threshold. Terrain data is presented for practitioner review. Clinical relevance is at the sole discretion of the treating practitioner.';

export function applyBorderlineTooltip(zone: ZoneOutput): ZoneOutput {
  if (zone.status === 'Borderline (near threshold)') {
    return { ...zone, borderlineTooltip: BORDERLINE_TOOLTIP };
  }
  return zone;
}

// --- Full Document Assembly ---

export function generateT01Output(content: ClinicalContent): string {
  const sections: string[] = [];

  // W5-1: Title
  sections.push(`# ${T01_TITLE}`);
  sections.push('');

  // W5-3: Protective header (PERMANENT — NEVER REVERT)
  sections.push(T01_PROTECTIVE_HEADER);
  sections.push('---');

  // W5-2: Fixed opening line
  sections.push(T01_OPENING_LINE);
  sections.push('');

  // W5-5: Terrain Resilience (suppressed CascadeIQ bands)
  sections.push(`## ${formatTerrainResilience(content.terrainResilience)}`);
  sections.push('');

  // Zone outputs with borderline tooltips
  sections.push('## Zone Assessment');
  for (const zone of content.zones) {
    const z = applyBorderlineTooltip(zone);
    sections.push(`**${z.zoneName}** (${z.zone}): ${z.score}/10 — ${z.status}`);
    if (z.borderlineTooltip) {
      sections.push(`> ${z.borderlineTooltip}`);
    }
  }
  sections.push('');

  // W5-6: DRD designation with display language
  if (content.drdDesignation) {
    sections.push('## Burden Designation');
    sections.push(formatDrdDesignation(content.drdDesignation));
    sections.push('');
  }

  // W5-7: Support considerations (filtered — supplements, dietary, lifestyle only)
  const filtered = filterPharmaceutical(content.supportConsiderations);
  if (filtered.length > 0) {
    sections.push('## Support Considerations');
    for (const item of filtered) {
      sections.push(`- **[${item.category.toUpperCase()}]** ${item.description} _(${item.evidenceTier})_ — Target: ${item.targetZone}`);
    }
    sections.push('');
  }

  sections.push('---');

  // W5-4: Practitioner Clinical Decision section (PERMANENT — NEVER REVERT)
  sections.push(T01_PRACTITIONER_DECISION_SECTION);
  sections.push('');

  // Regulatory footer
  sections.push('---');
  sections.push(VM_BRAND.regulatoryFooter);

  return sections.join('\n');
}

// --- Validation ---

export function validateT01Compliance(output: string): string[] {
  const violations: string[] = [];

  if (!output.includes(T01_TITLE)) {
    violations.push('W5-1: Missing title "Terrain Support Considerations"');
  }
  if (!output.includes(T01_OPENING_LINE)) {
    violations.push('W5-2: Missing fixed opening line');
  }
  if (!output.includes('IMPORTANT NOTICE')) {
    violations.push('W5-3 [PERMANENT]: Missing protective header');
  }
  if (!output.includes('PRACTITIONER CLINICAL DECISION')) {
    violations.push('W5-4 [PERMANENT]: Missing Practitioner Clinical Decision section');
  }
  if (/CascadeIQ\s*(band|score|level)/i.test(output)) {
    violations.push('W5-5: CascadeIQ band labels not suppressed');
  }
  if (/\bDriver\b/.test(output) && !/Highest burden zone/i.test(output)) {
    violations.push('W5-6: DRD "Driver" not replaced with "Highest burden zone"');
  }
  if (/\bReactor\b/.test(output) && !/Secondary burden zone/i.test(output)) {
    violations.push('W5-6: DRD "Reactor" not replaced with "Secondary burden zone"');
  }
  if (/pharmaceutical|medication|prescription|drug therapy/i.test(output)) {
    violations.push('W5-7: Pharmaceutical content detected — must be supplements, dietary, lifestyle only');
  }

  return violations;
}
